# Generated by Django 5.2.1 on 2025-09-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='filter',
        ),
        migrations.AddField(
            model_name='profile',
            name='filters',
            field=models.CharField(blank=True, help_text='Enter keywords separated by commas', max_length=300),
        ),
    ]
